arcUrl = 'https://arc.dev/remote-jobs'
vanHackUrl = 'https://vanhack.com/jobs'
TuringUrl = 'https://www.turing.com/jobs'
remoteUrl = 'https://remote.co/remote-jobs/'
jremoteUrl = 'https://justremote.co/remote-jobs'
remotiveUrl = 'https://remotive.com/'